### ISSUE TITLE
Creating the Home Page Front End

### ISSUE THREAD

**Issue by LeahTerra** [CMPUT301F21T17/Sisyphus#35]
The home page in our storyboard contains multiple data sets, and is essential for movement throughout the app. As such, to complete we must create a functional home menu ui containing buttons and links to many activities, and serve as the central location of the app.

It should contain a bottom navigation bar that leads to:
- Daily Habit View
- All Habits
- Social Feed
- Calendar View

As well, it should contain a add habit button on appropriate menus that links to the add habit activity, and a top navigational bar containing a drop down menu that leads to follow requests, logout, and potentially a settings menu if it is determined to be necessary.

**Comment by RealHorse** [comment]
Potential slight mislabeling on this issue.  The nature of the main menu dictates changes as the program evolves.  Modifying status to In Progress.  Note that major portions of the front-end work necessary to complete this task are finished at this point, but change is likely to be necessary in future.

**Comment by RealHorse** [comment]
Working and verified.  Closing.
